---
debug: false
server:
    port: 8888
    
spring:
    application:
        name: ms-config-server
    profiles:
        active: @spring.profiles.active@
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/fr33land/ms-config-repo
                    cloneOnStart: true
                   
eureka:
    client:
        serviceUrl:
            defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}   