language: java
sudo: required


env:
  matrix:
    - SERVICE_MODULE=ms-config-server
    - SERVICE_MODULE=ms-eureka-server
    - SERVICE_MODULE=ms-oauth-server
    - SERVICE_MODULE=ms-users-service
    - SERVICE_MODULE=ms-webapp-service
    
services:
- docker

script: 
- mvn clean install -Dmaven.test.skip=true

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=fr33land/$SERVICE_MODULE
- docker build -t $IMAGE_NAME:$COMMIT ./$SERVICE_MODULE
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
