---
server:
    port: 8081
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
            
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
        jpa:
            database: POSTGRESQL
            show-sql: true
            hibernate:
                ddl-auto: create-drop
                
security:
    basic:
        enabled: false