---
server:
    port: 8080
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
        jpa:
            database: POSTGRESQL
            show-sql: true
            hibernate:
                ddl-auto: create-drop
      
zuul:
    host:
        connect-timeout-millis: 50000
        socket-timeout-millis: 50000
    add-host-header: true
    add-proxy-headers: true
    routes:
        uaa:
            sensitiveHeaders:
            path: /uaa/**
            serviceId: auth-server
        users:
            sensitiveHeaders:
            path: /users/**
            serviceId: users-service
    include-debug-header: true
            

security:
    user:
        name: root
        password: password
    oauth2:
        client:
            clientId: zuul-server
            clientSecret: zuul-server
            scope: read
            accessTokenUri: http://localhost:8089/uaa/oauth/token
            userAuthorizationUri: http://localhost:8089/uaa/oauth/authorize
            clientAuthenticationScheme: form
        resource:
            userInfoUri: http://localhost:8089/uaa/user
            preferTokenInfo: false  
