---
spring:
    application:
        name: db-migration
        email: freeland.rokas@gmail.com
    datasource:
        url: jdbc:postgresql://192.168.8.104:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
                    
flyway:
   url: jdbc:postgresql://192.168.8.104:5432/freeland
   schemas: freeland
   user: freeland
   password: freeland
