---
server:
    port: 8089
#    servlet:
    context-path: /uaa
    
spring:
    application:
        name: auth-server
    datasource:
        url: jdbc:postgresql://localhost:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
                
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        
security:
    basic:    
        enabled: false
        
keystore:
    jks: jwtkey.jks
    keyname: jwtkey
    password: aaaaaa
        
logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG