---
server:
    port: 8081
    servlet:
        context-path: /ui
    # servlet: for spring boot2
    # context-path: /ui

spring:
    application:
        name: webapp-service
    thymeleaf:
        cache: false   

security:
    basic:
        enabled: false
    oauth2:
        client:
            clientId: webapp-server
            clientSecret: webapp-server
            accessTokenUri: http://localhost:8089/uaa/oauth/token
            userAuthorizationUri: http://localhost:8089/uaa/oauth/authorize
#            pre-established-redirect-uri: http://localhost:8081/ui/userProfile
#            registered-redirect-uri: http://localhost:8081/ui/userProfile
#            use-current-uri: false
        resource:
            userInfoUri: http://localhost:8089/uaa/user
            ssoLogoutUri: http://localhost:8089/uaa/ssoLogout
            tokenInvalidateUri: http://localhost:8089/uaa/invalidateToken
      
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/     
            
logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG