---
server:
    port: 8081
    context-path: /ui
    session:
        cookie:
            name: UISESSION

spring:
    application:
        name: webapp-ui
    thymeleaf:
        cache: false   
        
security:
    basic:
        enabled: false
    oauth2:
        client:
            clientId: webapp-server
            clientSecret: webapp-server
            accessTokenUri: http://localhost:8089/uaa/oauth/token
            userAuthorizationUri: http://localhost:8089/uaa/oauth/authorize
        resource:
            userInfoUri: http://localhost:8089/uaa/user
      
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/     